[package]
name = "zap-net"
description = "Encrypted UDP transport for ZAP."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
blake3.workspace = true
bytes.workspace = true
chacha20poly1305.workspace = true
hex.workspace = true
rand_core.workspace = true
serde.workspace = true
snow.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
zap-core = { path = "../zap-core" }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "round_trip"
harness = false
