[package]
name = "zap-driver-sdk"
description = "Helpers for writing ZAP WASM action drivers."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bitflags.workspace = true
blake3.workspace = true
bytes.workspace = true
hex.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
zap-capability.workspace = true

[dev-dependencies]
criterion.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "sdk"
harness = false
